spring.application.name=spring-aws-sandbox

spring.datasource.url=jdbc:h2:mem:spring-aws-sandbox;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

aws.sqs.endpoint=http://localhost:4566
aws.region=sa-east-1
aws.accountId=000008845000

sns.topic.pedido=arn:aws:sns:sa-east-1:000008845000:sns-pedido
sns.subject.pedido=pedido
sns.subject.notificacao=notificacao


spring.cloud.aws.region.static=sa-east-1
spring.cloud.aws.credentials.access-key=000008845000
spring.cloud.aws.credentials.secret-key=teste
spring.cloud.aws.sns.enabled=true
spring.cloud.aws.sns.endpoint=http://localhost:4566